### PR TITLE
Run e2e tests in tmp dir

### PR DESCRIPTION
**Pull request by natemcmaster**
Fixes tests in CI environments. They were failing due to max path length restrictions.

cc @bricelam

### CODE REVIEW

**Review by bricelam — APPROVED** [review]
:shipit:

**Comment by bricelam** [comment]
Why are the versions pinned to msbuild2 in the dev2 branch?

**Comment by natemcmaster** [comment]
They shouldn't be. I did a no-ff merge into dev2 and didn't bring back that change.

**Comment by bricelam** [comment]
Might just be a quirk of the diff on GitHub. I haven't checked the actual branch.

**Comment by bricelam** [comment]
Yep. The branch is right.

**Pull request merged**
