### PR TITLE
Add more-complete .gitattributes file

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by bricelam** [comment]
I am completely against this for several reasons:
1. All of those `diff` attributes are already defined by default in Git for Windows (not to mention we don't even have these kind of files any of our repos)
2. This is actually *less complete* because it misses `text=auto` on all of the text files not explicitly listed which leads to end-of-line character nightmares. (I noticed other repos already have issues like this with `*.cshtml` files.)
3. I have yet to see an issue with auto-detecting `text` vs `binary` on all files.

**Please revert to the original.** The two lines you can add to the original (if they actually, truly matter) are:

    *.sln eol=crlf
    *.sh eol=lf

cc @Eilon

**Comment by bricelam** [comment]
P.S. I filed aspnet/Universe#124 about this way back when

**Comment by bricelam** [comment]
Or, as @AndriySvyryd would say:

image

**Comment by dougbu** [comment]
I note aspnet/Universe#124 was closed a couple of months ago.

**Comment by bricelam** [comment]
I think it was just part of a bulk cleanup effort, but I'll let Eilon comment on whether we should be consistent across repos. Either way EF would like it's .gitattributes files to include `* text=auto` as we've been bitten in the past and have established it as a best practice.

**Comment by Eilon** [comment]
Hmm, yeah, closing https://github.com/aspnet/Universe/issues/124 was just bulk cleanup because no one had sad anything about it or complained in quite some time.

I have two questions:
1. Presumably because all our repos are fairly similar in structure, what reason is there why they shouldn't all have the same `.gitattributes` file?
2. What's wrong with the simple auto-detect one?

The reason I think that (1) is important is because we often run scripts across all repos to do bulk updates and if we have inconsistent line-endings treatment then I could foresee that causing problems.

**Comment by Eilon** [comment]
And... I re-opened https://github.com/aspnet/Universe/issues/124, because it seems like "someone should do something" 😄

**Pull request merged**
